[tool.poetry]
name = "eth-udk-navigator"
version = "0.1.0"
description = "Semantic Vector Search for ETH UDK with MMS-ID Lookups"
authors = ["Germano Giuliani <germano@example.com>"]

[tool.poetry.dependencies]
python = ">=3.11.0,<3.12"
flask = "^3.0.0"
gunicorn = "^21.2.0"
flask-cors = "^5.0.0"
openai = "^1.68.2"
pinecone = "^6.0.2"
python-dotenv = "^1.0.1"
requests = "^2.32.3"
beautifulsoup4 = "^4.13.3"
pymupdf = "^1.25.4"

[tool.pyright]
useLibraryCodeForTypes = true
exclude = [".cache"]

[tool.ruff]
select = ['E', 'W', 'F', 'I', 'B', 'C4', 'ARG', 'SIM']
ignore = ['W291', 'W292', 'W293']

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
